# PATHS INCLUDED/EXCLUDED
# paths to include during linting. `--path` is ignored if present.
included:
  - Source
  #- XCodeTemplates
  
# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - Pods

# RULES
# Find all the available rules by running:
# swiftlint rules

# rule identifiers to exclude from running
disabled_rules:
   - trailing_whitespace
   - identifier_name
   
  # other disabled_rules
  #- cyclomatic_complexity
  #- function_body_length
  #- colon
  #- comma
  #- control_statement

# some rules are only opt-in
opt_in_rules:
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_nimble
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_outlet
  - private_subject
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation #???
  - required_enum_case
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition
  
  # other opt_in_rules
  #- conditional_returns_on_newline
  #- discouraged_optional_collection
  #- explicit_acl
  #- explicit_enum_raw_value
  #- explicit_top_level_acl
  #- explicit_type_interface
  #- file_name
  #- file_types_order
  #- first_where
  #- ibinspectable_in_extension
  #- indentation_width
  #- multiline_parameters_brackets
  #- no_extension_access_modifier
  #- no_grouping_extension
  #- no_magic_numbers
  #- period_spacing
  #- private_action
  #- prohibited_interface_builder
  #- required_deinit
  #- trailing_closure
  #- type_contents_order
  #- vertical_whitespace_between_cases
  #- vertical_whitespace_closing_braces
  #- vertical_whitespace_opening_braces

  
# OTHER
# Rules run by `swiftlint analyze` (experimental)
analyzer_rules:
  - capture_variable
  - explicit_self
  - typesafe_array_init
  - unused_declaration
  - unused_import

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

# FILE LENGTHS
# naming rules can set warnings/errors for min_length and max_length
file_length: 500
line_length: 170
function_parameter_count: 15
type_body_length: 450
cyclomatic_complexity: 20

# PART OF FILE
type_body_length: 300

type_name:
  min_length: 3
  max_length: 40
  # excluded via string
  excluded:
  - iPhone
  - id
  - ad
  # these are allowed in type names
  allowed_symbols: ["_"]

identifier_name:
  min_length: 2

# excluded via string array
excluded:
    - id
    - URL
    
# SHOW MESSAGES
reporter: "xcode"
